version: '3.8'

services:
  mysql-db:
    image: bitnami/mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: monitoring
    volumes:
      - /home/${SSH_USER}/deploy/mysql:/bitnami/mysql
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
        
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db
    ports:
      - "8081:80"  # Access phpMyAdmin at http://localhost:8081
    depends_on:
      - mysql-db
        
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"      # MQTT port
      - "9001:9001"      # WebSocket port (optional)
    volumes:
      - /home/${SSH_USER}/deploy/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /home/${SSH_USER}/deploy/mosquitto/data:/mosquitto/data
      - /home/${SSH_USER}/deploy/mosquitto/log:/mosquitto/log

  monitoring-backend:
    image: ghcr.io/proteus1121/monitoring-backend:latest
    container_name: monitoring-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PROFILE: ${PROFILE}
      MYSQL_PASS: ${MYSQL_PASS}
    depends_on:
      - mysql-db
        
  monitoring-frontend:
    image: ghcr.io/proteus1121/monitoring-frontend:latest
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: monitoring-frontend
    ports:
      - "80:80"
    depends_on:
      - mysql-db
