entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

log:
  level: DEBUG
  filePath: "/var/log/traefik/traefik.log"

providers:
  docker:
    swarmMode: true
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: artem.ischchenko@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web