[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    beegee-tokyo/DHT sensor library for ESPx@1.19
    adafruit/Adafruit BMP085 Library@1.2.4
    olikraus/U8g2@2.36.12
    knolleary/PubSubClient@2.8
    bblanchon/ArduinoJson@7.4.2
